version: '2'
services:
  db:
    image: postgres:10
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=111"
      - "POSTGRES_DB=simple"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  app:
    image: my-golang-app
    ports:
      - "3000:3000"